### PR TITLE
Migrate to macOS M1 runner

### LINKED ISSUE #310: Use aarch64 MacOS on CI
### Feature Request

Test on Macos M1 runner to improve CI speed.
Waiting on addition of Macos M1 runner.
- [x] https://github.com/github/roadmap/issues/52
- [ ] Small runners are available
- [ ] Android NDK is preinstalled 
- [x] Update checks.yml
- [ ] Update compileContracts.sh

### PR DESCRIPTION
**Pull request by DelevoXDG**
## Describe your changes

- [x] Change runner: `macos-latest` -> `macos-latest-xlarge`
- [x] Remove macOS x64 related steps from workflow

## Linked issues

Closes #310 

## Breaking changes

- [ ] This issue contains breaking changes

### CODE REVIEW

**Comment by DelevoXDG** [comment]
Apparently, Android NDK is currently not preinstalled. Tracking https://github.com/actions/runner-images/issues/8439 .

**Comment by THenry14** [comment]
Is m1 free to use? or is it paid?

**Comment by DelevoXDG** [comment]
> Is m1 free to use? or is it paid?

Seems like paid-only for now (no small runners for now), so one more reason to hold this off.

**Comment by DelevoXDG** [comment]
https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587

Seems like the small runners will be available far in the future. 
Additionally, #345 will be addressed before that, mostly removing the primary reason for migration. By then, it is likely this PR will be no longer relevant.

**Comment by kgantchev** [comment]
> [actions/runner-images#8439 (comment)](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587)
> 
> Seems like the small runners will be available only far in the future.

Might I make a suggestion here? You can try the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners which are on average about 2x faster and 2x cheaper than GitHub's runners ._ **We also offer a free tier of 500 mins/month on the M1 runner for OSS projects.**_

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label                          | Price on FlyCI | Price on GitHub |
|-----------|------|----------|---------|--------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB   | flyci-macos-large-latest-m1    | $0.06          | -             |
| M1        | 8    | 14       | 28 GB   | flyci-macos-xlarge-latest-m1   | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB   | flyci-macos-large-latest-m2    | $0.08          | -             |
| M2        | 8    | 14       | 28 GB   | flyci-macos-xlarge-latest-m2   | $0.16          | -             |

## Guide for Implementation

1. Install the [FlyCI GitHub app](https://github.com/apps/flyci-prod).
2. Modify the `runs-on` directive in workflow files as demonstrated in this PR.
4. Enjoy enhanced efficiency in CI builds with the integration of FlyCI's MacOS runners.

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
 
We'll be very happy to have you on board.

**Pull request closed without merging**
